<?php
if (!defined('KIRPI_CORE_ENTRY')) {
    exit;
}

function template_lang(string $key, ?string $default = null): string
{
    static $dictionary = [
        'tr' => [
            'templates' => 'Template Registry',
            'email_templates' => 'E-posta Şablonları',
            'print_templates' => 'Yazdırma Şablonları',
            'content_templates' => 'İçerik Şablonları',
            'templates_hint' => 'E-posta, yazdırma ve sistem içerik şablonları merkezi olarak yönetilir.',
            'new_template' => 'Yeni Şablon',
            'edit_template' => 'Şablon Düzenle',
            'template_list' => 'Şablon Listesi',
            'filters' => 'Filtreler',
            'search' => 'Arama',
            'search_placeholder' => 'Ad, konu, hedef veya içerikte ara...',
            'filter' => 'Filtrele',
            'clear' => 'Temizle',
            'all_modules' => 'Tüm Modüller',
            'all_statuses' => 'Tüm Durumlar',
            'export_csv' => 'CSV',
            'export_excel' => 'Excel',
            'kind' => 'Tür',
            'kind_email' => 'E-posta',
            'kind_print' => 'Yazdırma',
            'kind_content' => 'İçerik',
            'module' => 'Modül',
            'target' => 'Hedef',
            'code' => 'Kod',
            'name' => 'Ad',
            'language' => 'Dil',
            'subject' => 'Konu',
            'body' => 'İçerik',
            'variables' => 'Değişkenler',
            'template_origin' => 'Kaynak',
            'status' => 'Durum',
            'active' => 'Aktif',
            'inactive' => 'Pasif',
            'system' => 'Sistem',
            'custom' => 'Özel',
            'actions' => 'İşlemler',
            'save' => 'Kaydet',
            'update' => 'Güncelle',
            'toggle_status' => 'Durum Değiştir',
            'no_records' => 'Şablon kaydı yok.',
            'table_missing' => 'templates tablosu kurulu değil. Ayarlar > Eksikleri Kur çalıştırın.',
            'required_fields' => 'Tür, modül, hedef, kod, ad, dil ve içerik zorunludur.',
            'invalid_kind' => 'Geçersiz şablon türü.',
            'invalid_code' => 'Kod formatı geçersiz.',
            'created_success' => 'Şablon oluşturuldu.',
            'updated_success' => 'Şablon güncellendi.',
            'status_updated' => 'Şablon durumu güncellendi.',
            'not_found' => 'Şablon bulunamadı.',
            'save_error' => 'Şablon kaydedilirken bir hata oluştu.',
            'duplicate' => 'Bu kapsamda aynı kod zaten kullanılıyor.',
            'code_hint' => 'Küçük harf, rakam, nokta, tire ve alt çizgi kullanın.',
            'variables_hint' => 'Virgül ile ayırın. Örnek: app_name,user_name',
            'back_to_mail' => 'Mail Teste Dön',
            'created_at' => 'Oluşturulma',
            'updated_at' => 'Güncelleme',
        ],
        'en' => [
            'templates' => 'Template Registry',
            'email_templates' => 'Email Templates',
            'print_templates' => 'Print Templates',
            'content_templates' => 'Content Templates',
            'templates_hint' => 'Email, print, and system content templates are managed centrally.',
            'new_template' => 'New Template',
            'edit_template' => 'Edit Template',
            'template_list' => 'Template List',
            'filters' => 'Filters',
            'search' => 'Search',
            'search_placeholder' => 'Search name, subject, target, or body...',
            'filter' => 'Filter',
            'clear' => 'Clear',
            'all_modules' => 'All Modules',
            'all_statuses' => 'All Statuses',
            'export_csv' => 'CSV',
            'export_excel' => 'Excel',
            'kind' => 'Kind',
            'kind_email' => 'Email',
            'kind_print' => 'Print',
            'kind_content' => 'Content',
            'module' => 'Module',
            'target' => 'Target',
            'code' => 'Code',
            'name' => 'Name',
            'language' => 'Language',
            'subject' => 'Subject',
            'body' => 'Body',
            'variables' => 'Variables',
            'template_origin' => 'Origin',
            'status' => 'Status',
            'active' => 'Active',
            'inactive' => 'Inactive',
            'system' => 'System',
            'custom' => 'Custom',
            'actions' => 'Actions',
            'save' => 'Save',
            'update' => 'Update',
            'toggle_status' => 'Toggle Status',
            'no_records' => 'No templates found.',
            'table_missing' => 'templates table is not installed. Run Settings > Install Missing.',
            'required_fields' => 'Kind, module, target, code, name, language, and body are required.',
            'invalid_kind' => 'Invalid template kind.',
            'invalid_code' => 'Invalid code format.',
            'created_success' => 'Template created.',
            'updated_success' => 'Template updated.',
            'status_updated' => 'Template status updated.',
            'not_found' => 'Template not found.',
            'save_error' => 'An error occurred while saving template.',
            'duplicate' => 'The same code is already used in this scope.',
            'code_hint' => 'Use lowercase letters, numbers, dots, dashes, and underscores.',
            'variables_hint' => 'Separate with commas. Example: app_name,user_name',
            'back_to_mail' => 'Back to Mail Test',
            'created_at' => 'Created At',
            'updated_at' => 'Updated At',
        ],
    ];

    $locale = strtolower((string) env('APP_LOCALE', 'tr'));
    if (!isset($dictionary[$locale])) {
        $locale = 'tr';
    }

    return $dictionary[$locale][$key] ?? $dictionary['tr'][$key] ?? $default ?? $key;
}
