<?php
if (!defined('KIRPI_CORE_ENTRY')) exit;
require_once BASE_PATH . '/modules/governance/language.php'; require_once BASE_PATH . '/modules/governance/helpers.php';
$resource=trim((string)($_GET['resource']??'')); $id=(int)($_GET['id']??0); $config=governance_resource_config($resource);
if(!$config){echo '<div class="modal-body"><div class="alert alert-danger">'.e(governance_lang('invalid_resource')).'</div></div>';exit;}
if(!check_permission($config['permission'])){echo '<div class="modal-body"><div class="alert alert-danger">'.e(governance_lang('permission_denied')).'</div></div>';exit;}
$record=[]; if($id>0){$stmt=db()->prepare("SELECT * FROM {$config['table']} WHERE id=:id");$stmt->execute([':id'=>$id]);$record=$stmt->fetch(PDO::FETCH_ASSOC)?:[];if(!$record||!organization_company_in_scope((int)$record['company_id'])){echo '<div class="modal-body"><div class="alert alert-danger">'.e(governance_lang('permission_denied')).'</div></div>';exit;}}
$options=governance_select_options(); $v=static fn(string $key,string $default='')=>(string)($record[$key]??$default);
$title=$resource==='ownerships'?governance_lang($id?'edit_ownership':'new_ownership'):governance_lang($id?'edit_delegation':'new_delegation');
?>
<div class="modal-header"><h5 class="modal-title"><?php echo e($title); ?></h5><button type="button" class="btn-close" data-bs-dismiss="modal"></button></div>
<form id="governance-form" action="<?php echo base_url('governance/actions/save'); ?>" method="post" data-ajax="true" data-close-modal="true"><div class="modal-body"><input type="hidden" name="csrf_token" value="<?php echo e(get_csrf_token()); ?>"><input type="hidden" name="resource" value="<?php echo e($resource); ?>"><input type="hidden" name="id" value="<?php echo $id; ?>"><div class="row g-3">
<div class="col-md-6"><label class="form-label form-required"><?php echo e(governance_lang('company')); ?></label><select name="company_id" class="form-select" data-governance-company required><option value=""><?php echo e(governance_lang('select_company')); ?></option><?php foreach($options['companies'] as $o):?><option value="<?php echo (int)$o['id']; ?>" <?php echo (int)$v('company_id')===(int)$o['id']?'selected':'';?>><?php echo e($o['company_code'].' - '.$o['company_name']); ?></option><?php endforeach;?></select></div>
<?php if($resource==='ownerships'): ?>
<div class="col-md-6"><label class="form-label form-required"><?php echo e(governance_lang('subject_type')); ?></label><select name="subject_type" class="form-select" required><option value=""><?php echo e(governance_lang('select_subject')); ?></option><?php foreach(governance_subject_types() as $type):?><option value="<?php echo e($type); ?>" <?php echo $v('subject_type')===$type?'selected':'';?>><?php echo e(governance_lang($type)); ?></option><?php endforeach;?></select></div>
<div class="col-md-4"><label class="form-label form-required"><?php echo e(governance_lang('subject_id')); ?></label><input type="number" min="1" name="subject_id" class="form-control" value="<?php echo e($v('subject_id')); ?>" required></div><div class="col-md-8"><label class="form-label form-required"><?php echo e(governance_lang('subject_title')); ?></label><input name="subject_title" maxlength="190" class="form-control" value="<?php echo e($v('subject_title')); ?>" required></div>
<div class="col-md-6"><label class="form-label form-required"><?php echo e(governance_lang('ownership_type')); ?></label><select name="ownership_type" class="form-select" required><?php foreach(governance_ownership_types() as $type):?><option value="<?php echo e($type); ?>" <?php echo $v('ownership_type')===$type?'selected':'';?>><?php echo e(governance_lang($type)); ?></option><?php endforeach;?></select></div><div class="col-md-6"><label class="form-label form-required"><?php echo e(governance_lang('owner')); ?></label><select name="owner_user_id" class="form-select" data-company-user required><option value=""><?php echo e(governance_lang('select_user')); ?></option><?php foreach($options['users'] as $o):?><option value="<?php echo (int)$o['id']; ?>" data-company-ids="<?php echo e(implode(',', $o['company_ids'])); ?>" <?php echo (int)$v('owner_user_id')===(int)$o['id']?'selected':'';?>><?php echo e($o['name'].' ('.$o['email'].')'); ?></option><?php endforeach;?></select></div>
<?php else: ?>
<div class="col-md-6"><label class="form-label form-required"><?php echo e(governance_lang('from_user')); ?></label><select name="from_user_id" class="form-select" data-company-user required><option value=""><?php echo e(governance_lang('select_user')); ?></option><?php foreach($options['users'] as $o):?><option value="<?php echo (int)$o['id']; ?>" data-company-ids="<?php echo e(implode(',', $o['company_ids'])); ?>" <?php echo (int)$v('from_user_id')===(int)$o['id']?'selected':'';?>><?php echo e($o['name'].' ('.$o['email'].')'); ?></option><?php endforeach;?></select></div><div class="col-md-6"><label class="form-label form-required"><?php echo e(governance_lang('to_user')); ?></label><select name="to_user_id" class="form-select" data-company-user required><option value=""><?php echo e(governance_lang('select_user')); ?></option><?php foreach($options['users'] as $o):?><option value="<?php echo (int)$o['id']; ?>" data-company-ids="<?php echo e(implode(',', $o['company_ids'])); ?>" <?php echo (int)$v('to_user_id')===(int)$o['id']?'selected':'';?>><?php echo e($o['name'].' ('.$o['email'].')'); ?></option><?php endforeach;?></select></div>
<?php endif; ?>
<div class="col-md-6"><label class="form-label"><?php echo e(governance_lang('starts_on')); ?></label><input type="date" name="starts_on" class="form-control" value="<?php echo e($v('starts_on')); ?>" <?php echo $resource==='delegations'?'required':''; ?>></div><div class="col-md-6"><label class="form-label"><?php echo e(governance_lang('ends_on')); ?></label><input type="date" name="ends_on" class="form-control" value="<?php echo e($v('ends_on')); ?>" <?php echo $resource==='delegations'?'required':''; ?>></div>
<div class="col-12"><label class="form-label <?php echo $resource==='delegations'?'form-required':''; ?>"><?php echo e(governance_lang('reason')); ?></label><textarea name="reason" class="form-control" rows="3" <?php echo $resource==='delegations'?'required':''; ?>><?php echo e($v($resource==='ownerships'?'notes':'reason')); ?></textarea></div>
</div></div><div class="modal-footer"><button type="button" class="btn me-auto" data-bs-dismiss="modal"><?php echo e(governance_lang('cancel')); ?></button><button type="submit" class="btn btn-primary"><?php echo e(governance_lang($id?'update':'save')); ?></button></div></form>
