<?php
if (!defined('KIRPI_CORE_ENTRY')) exit;
require_once BASE_PATH . '/modules/organization/language.php';require_once BASE_PATH . '/modules/organization/helpers.php';
$resource=trim((string)($_GET['resource']??'companies'));$format=trim((string)($_GET['format']??'csv'));if(!organization_resource_config($resource)){http_response_code(422);exit(organization_lang('invalid_resource'));}
$search=trim((string)($_GET['search']??''));$status=trim((string)($_GET['status']??''));$where=[];$params=[];if($status!==''){$where[]='x.status=:status';$params[':status']=$status;}
$defs=[
'companies'=>['from'=>'organization_companies x','search'=>['x.company_code','x.company_name','x.legal_name'],'select'=>'x.company_code,x.company_name,x.legal_name,x.status,x.created_at,x.updated_at','headers'=>[organization_lang('company_code'),organization_lang('company_name'),organization_lang('legal_name'),organization_lang('status'),organization_lang('created_at'),organization_lang('updated_at')]],
'units'=>['from'=>'organization_units x JOIN organization_companies c ON c.id=x.company_id LEFT JOIN organization_units p ON p.id=x.parent_unit_id','search'=>['x.unit_code','x.unit_name','c.company_name'],'select'=>'x.unit_code,x.unit_name,x.unit_type,c.company_name,p.unit_name AS parent_name,x.status','headers'=>[organization_lang('unit_code'),organization_lang('unit_name'),organization_lang('unit_type'),organization_lang('company'),organization_lang('parent_unit'),organization_lang('status')]],
'positions'=>['from'=>'organization_positions x JOIN organization_companies c ON c.id=x.company_id LEFT JOIN organization_units d ON d.id=x.department_unit_id','search'=>['x.position_code','x.position_name','c.company_name'],'select'=>'x.position_code,x.position_name,c.company_name,d.unit_name AS department_name,x.status','headers'=>[organization_lang('position_code'),organization_lang('position_name'),organization_lang('company'),organization_lang('department'),organization_lang('status')]],
'assignments'=>['from'=>'organization_user_assignments x JOIN users u ON u.id=x.user_id JOIN organization_companies c ON c.id=x.company_id LEFT JOIN organization_units ou ON ou.id=x.unit_id LEFT JOIN organization_positions p ON p.id=x.position_id','search'=>['u.name','u.email','c.company_name','ou.unit_name','p.position_name'],'select'=>'u.name,u.email,c.company_name,ou.unit_name,p.position_name,x.scope_mode,x.is_primary,x.status,x.starts_at,x.ends_at','headers'=>[organization_lang('user'),'E-posta',organization_lang('company'),organization_lang('unit'),organization_lang('position'),organization_lang('scope_mode'),organization_lang('is_primary'),organization_lang('status'),organization_lang('starts_at'),organization_lang('ends_at')]],
];$def=$defs[$resource];$scopeWhere=organization_scope_where($resource==='companies'?'x.id':'x.company_id',$params);if($scopeWhere!==null)$where[]=$scopeWhere;if($search!==''){$parts=[];foreach($def['search'] as $i=>$col){$key=':s'.$i;$parts[]="$col LIKE $key";$params[$key]='%'.$search.'%';}$where[]='('.implode(' OR ',$parts).')';}$sql='SELECT '.$def['select'].' FROM '.$def['from'].($where?' WHERE '.implode(' AND ',$where):'').' ORDER BY x.id DESC LIMIT 5000';$stmt=db()->prepare($sql);$stmt->execute($params);$rows=[];while($row=$stmt->fetch(PDO::FETCH_NUM)){$rows[]=$row;}kirpi_export_response($format,'organization-'.$resource.'-'.date('Ymd-His'),$def['headers'],$rows);
