<?php
if (!defined('KIRPI_CORE_ENTRY')) exit;
require_once BASE_PATH . '/modules/organization/language.php';require_once BASE_PATH . '/modules/organization/helpers.php';require_action('POST',true);
if(!verify_csrf_token($_POST['csrf_token']??null))json_response(['status'=>'error','message'=>'CSRF'],419);
$resource=trim((string)($_POST['resource']??''));$id=(int)($_POST['id']??0);$config=organization_resource_config($resource);if(!$config)json_response(['status'=>'error','message'=>organization_lang('invalid_resource')],422);
$permission=$id>0?$config['edit']:$config['create'];if(!check_permission($permission))json_response(['status'=>'error','message'=>organization_lang('permission_denied')],403);
$userId=(int)(current_user()['id']??0);$status=isset($_POST['is_active'])?'active':'inactive';
try{
 db()->beginTransaction();
 if($resource==='companies'){
  $code=organization_normalize_code((string)($_POST['company_code']??''));$name=trim((string)($_POST['company_name']??''));if(!organization_valid_code($code)||$name==='')throw new InvalidArgumentException(organization_lang($name===''?'required_fields':'invalid_code'));
  if((current_user()['role_name']??'')!=='Super Admin'&&($id<=0||!organization_company_in_scope($id)))throw new RuntimeException(organization_lang('permission_denied'),403);$dup=db()->prepare('SELECT COUNT(*) FROM organization_companies WHERE company_code=:code AND id<>:id');$dup->execute([':code'=>$code,':id'=>$id]);if((int)$dup->fetchColumn()>0)throw new InvalidArgumentException(organization_lang('duplicate_code'));
  $data=[':code'=>$code,':name'=>$name,':legal'=>trim((string)($_POST['legal_name']??''))?:null,':office'=>trim((string)($_POST['tax_office']??''))?:null,':number'=>trim((string)($_POST['tax_number']??''))?:null,':status'=>$status,':user'=>$userId];
  if($id){$data[':id']=$id;$sql='UPDATE organization_companies SET company_code=:code,company_name=:name,legal_name=:legal,tax_office=:office,tax_number=:number,status=:status,updated_by_user_id=:user WHERE id=:id';}else{unset($data[':user']);$data[':created_user']=$userId;$data[':updated_user']=$userId;$sql='INSERT INTO organization_companies(company_code,company_name,legal_name,tax_office,tax_number,status,created_by_user_id,updated_by_user_id) VALUES(:code,:name,:legal,:office,:number,:status,:created_user,:updated_user)';}
 }elseif($resource==='units'){
  $company=(int)($_POST['company_id']??0);$parent=(int)($_POST['parent_unit_id']??0);$type=trim((string)($_POST['unit_type']??''));$code=organization_normalize_code((string)($_POST['unit_code']??''));$name=trim((string)($_POST['unit_name']??''));if($company<=0||!in_array($type,organization_allowed_unit_types(),true)||!organization_valid_code($code)||$name==='')throw new InvalidArgumentException(organization_lang('required_fields'));if(!organization_company_in_scope($company))throw new RuntimeException(organization_lang('permission_denied'),403);
  if($parent>0&&(!organization_record_belongs_to_company('organization_units',$parent,$company)||$parent===$id))throw new InvalidArgumentException(organization_lang('invalid_hierarchy'));
  $dup=db()->prepare('SELECT COUNT(*) FROM organization_units WHERE company_id=:company AND unit_code=:code AND id<>:id');$dup->execute([':company'=>$company,':code'=>$code,':id'=>$id]);if((int)$dup->fetchColumn()>0)throw new InvalidArgumentException(organization_lang('duplicate_code'));
  $data=[':company'=>$company,':parent'=>$parent?:null,':type'=>$type,':code'=>$code,':name'=>$name,':description'=>trim((string)($_POST['description']??''))?:null,':sort'=>(int)($_POST['sort_order']??100),':status'=>$status,':user'=>$userId];
  if($id){$data[':id']=$id;$sql='UPDATE organization_units SET company_id=:company,parent_unit_id=:parent,unit_type=:type,unit_code=:code,unit_name=:name,description=:description,sort_order=:sort,status=:status,updated_by_user_id=:user WHERE id=:id';}else{unset($data[':user']);$data[':created_user']=$userId;$data[':updated_user']=$userId;$sql='INSERT INTO organization_units(company_id,parent_unit_id,unit_type,unit_code,unit_name,description,sort_order,status,created_by_user_id,updated_by_user_id) VALUES(:company,:parent,:type,:code,:name,:description,:sort,:status,:created_user,:updated_user)';}
 }elseif($resource==='positions'){
  $company=(int)($_POST['company_id']??0);$department=(int)($_POST['department_unit_id']??0);$code=organization_normalize_code((string)($_POST['position_code']??''));$name=trim((string)($_POST['position_name']??''));if($company<=0||!organization_valid_code($code)||$name==='')throw new InvalidArgumentException(organization_lang('required_fields'));if(!organization_company_in_scope($company))throw new RuntimeException(organization_lang('permission_denied'),403);
  if($department>0){$p=db()->prepare("SELECT COUNT(*) FROM organization_units WHERE id=:id AND company_id=:company AND unit_type='department'");$p->execute([':id'=>$department,':company'=>$company]);if(!(int)$p->fetchColumn())throw new InvalidArgumentException(organization_lang('invalid_hierarchy'));}
  $dup=db()->prepare('SELECT COUNT(*) FROM organization_positions WHERE company_id=:company AND position_code=:code AND id<>:id');$dup->execute([':company'=>$company,':code'=>$code,':id'=>$id]);if((int)$dup->fetchColumn()>0)throw new InvalidArgumentException(organization_lang('duplicate_code'));
  $data=[':company'=>$company,':department'=>$department?:null,':code'=>$code,':name'=>$name,':description'=>trim((string)($_POST['description']??''))?:null,':status'=>$status,':user'=>$userId];
  if($id){$data[':id']=$id;$sql='UPDATE organization_positions SET company_id=:company,department_unit_id=:department,position_code=:code,position_name=:name,description=:description,status=:status,updated_by_user_id=:user WHERE id=:id';}else{unset($data[':user']);$data[':created_user']=$userId;$data[':updated_user']=$userId;$sql='INSERT INTO organization_positions(company_id,department_unit_id,position_code,position_name,description,status,created_by_user_id,updated_by_user_id) VALUES(:company,:department,:code,:name,:description,:status,:created_user,:updated_user)';}
 }else{
  $uid=(int)($_POST['user_id']??0);$company=(int)($_POST['company_id']??0);$unit=(int)($_POST['unit_id']??0);$position=(int)($_POST['position_id']??0);$scope=trim((string)($_POST['scope_mode']??'self'));$starts=trim((string)($_POST['starts_at']??''));$ends=trim((string)($_POST['ends_at']??''));if($uid<=0||$company<=0||!in_array($scope,organization_allowed_scope_modes(),true))throw new InvalidArgumentException(organization_lang('required_fields'));if(!organization_company_in_scope($company))throw new RuntimeException(organization_lang('permission_denied'),403);if(!organization_valid_date($starts)||!organization_valid_date($ends))throw new InvalidArgumentException(organization_lang('invalid_date_range'));if($starts&&$ends&&$ends<$starts)throw new InvalidArgumentException(organization_lang('invalid_date_range'));
  foreach([['organization_units',$unit],['organization_positions',$position]] as [$table,$target]){if($target>0&&!organization_record_belongs_to_company($table,$target,$company))throw new InvalidArgumentException(organization_lang('invalid_hierarchy'));}
  $data=[':uid'=>$uid,':company'=>$company,':unit'=>$unit?:null,':position'=>$position?:null,':scope'=>$scope,':primary'=>isset($_POST['is_primary'])?1:0,':starts'=>$starts!==''?$starts.' 00:00:00':null,':ends'=>$ends!==''?$ends.' 23:59:59':null,':reason'=>trim((string)($_POST['assignment_reason']??''))?:null,':user'=>$userId];
  if($id){$data[':id']=$id;$sql='UPDATE organization_user_assignments SET user_id=:uid,company_id=:company,unit_id=:unit,position_id=:position,scope_mode=:scope,is_primary=:primary,starts_at=:starts,ends_at=:ends,assignment_reason=:reason,updated_by_user_id=:user WHERE id=:id';}else{unset($data[':user']);$data[':created_user']=$userId;$data[':updated_user']=$userId;$sql="INSERT INTO organization_user_assignments(user_id,company_id,unit_id,position_id,scope_mode,is_primary,status,starts_at,ends_at,assignment_reason,created_by_user_id,updated_by_user_id) VALUES(:uid,:company,:unit,:position,:scope,:primary,'active',:starts,:ends,:reason,:created_user,:updated_user)";}
 }
 $stmt=db()->prepare($sql);$stmt->execute($data);$recordId=$id?:((int)db()->lastInsertId());kirpi_audit_log($id?'update':'create','organization',['resource'=>$resource],$config['entity'],$recordId,'success');db()->commit();$row=organization_resource_row($resource,$recordId);json_response(['status'=>'success','message'=>organization_lang($id?'updated_success':'created_success'),'data'=>['id'=>$recordId,'resource'=>$resource,'row'=>$row]]);
}catch(InvalidArgumentException $e){if(db()->inTransaction())db()->rollBack();json_response(['status'=>'error','message'=>$e->getMessage()],422);}catch(RuntimeException $e){if(db()->inTransaction())db()->rollBack();if($e->getCode()===403)json_response(['status'=>'error','message'=>$e->getMessage()],403);throw $e;}catch(Throwable $e){if(db()->inTransaction())db()->rollBack();error_log('organization save error: '.$e->getMessage());json_response(['status'=>'error','message'=>organization_lang('save_error')],500);}
