<?php

function qms_relationships_lang(string $key, ?string $fallback = null): string
{
    $lang = function_exists('current_language') ? current_language() : 'tr';
    $d = [
        'tr' => [
            'qms_relationships' => 'Iliski Haritasi',
            'hint' => 'QMS varliklari arasindaki dogrudan, referans, kanit ve bagimlilik iliskilerini yonetin.',
            'new_relationship' => 'Yeni Iliski',
            'edit_relationship' => 'Iliskiyi Duzenle',
            'source_entity' => 'Kaynak Varlik',
            'target_entity' => 'Hedef Varlik',
            'relationship_type' => 'Iliski Turu',
            'relationship_kind' => 'Iliski Sinifi',
            'company' => 'Sirket',
            'description' => 'Aciklama',
            'evidence_strength' => 'Kanit Gucu',
            'status' => 'Durum',
            'active' => 'Aktif',
            'inactive' => 'Pasif',
            'archived' => 'Arsivlendi',
            'valid_from' => 'Baslangic',
            'valid_until' => 'Bitis',
            'created_at' => 'Olusturulma',
            'actions' => 'Islemler',
            'edit' => 'Duzenle',
            'archive' => 'Arsivle',
            'save' => 'Kaydet',
            'cancel' => 'Vazgec',
            'select_company' => 'Sirket secin',
            'select_entity' => 'Varlik secin',
            'select_type' => 'Iliski turu secin',
            'none' => 'Yok',
            'required_fields' => 'Zorunlu alanlari eksiksiz doldurun.',
            'invalid_record' => 'Iliski kaydi bulunamadi.',
            'invalid_entity_scope' => 'Secilen varliklar ayni sirket ve organizasyon kapsaminda olmalidir.',
            'same_entity_error' => 'Kaynak ve hedef varlik ayni olamaz.',
            'invalid_date_range' => 'Bitis tarihi baslangic tarihinden once olamaz.',
            'permission_denied' => 'Bu islem organizasyon kapsaminizda degil.',
            'created_success' => 'Iliski kaydi olusturuldu.',
            'updated_success' => 'Iliski kaydi guncellendi.',
            'archive_success' => 'Iliski kaydi arsivlendi.',
            'save_error' => 'Iliski kaydedilemedi.',
            'archive_error' => 'Iliski arsivlenemedi.',
        ],
        'en' => [
            'qms_relationships' => 'Relationship Map',
            'hint' => 'Manage direct, reference, evidence, and dependency links between QMS entities.',
            'new_relationship' => 'New Relationship',
            'edit_relationship' => 'Edit Relationship',
            'source_entity' => 'Source Entity',
            'target_entity' => 'Target Entity',
            'relationship_type' => 'Relationship Type',
            'relationship_kind' => 'Relationship Kind',
            'company' => 'Company',
            'description' => 'Description',
            'evidence_strength' => 'Evidence Strength',
            'status' => 'Status',
            'active' => 'Active',
            'inactive' => 'Inactive',
            'archived' => 'Archived',
            'valid_from' => 'Valid From',
            'valid_until' => 'Valid Until',
            'created_at' => 'Created At',
            'actions' => 'Actions',
            'edit' => 'Edit',
            'archive' => 'Archive',
            'save' => 'Save',
            'cancel' => 'Cancel',
            'select_company' => 'Select company',
            'select_entity' => 'Select entity',
            'select_type' => 'Select relationship type',
            'none' => 'None',
            'required_fields' => 'Complete all required fields.',
            'invalid_record' => 'Relationship record not found.',
            'invalid_entity_scope' => 'Selected entities must be in the same company and organization scope.',
            'same_entity_error' => 'Source and target entities cannot be the same.',
            'invalid_date_range' => 'End date cannot be before start date.',
            'permission_denied' => 'This action is outside your organization scope.',
            'created_success' => 'Relationship created.',
            'updated_success' => 'Relationship updated.',
            'archive_success' => 'Relationship archived.',
            'save_error' => 'Relationship could not be saved.',
            'archive_error' => 'Relationship could not be archived.',
        ],
    ];

    return $d[$lang][$key] ?? $d['tr'][$key] ?? $fallback ?? $key;
}
