<?php
define('BASE_PATH',dirname(__DIR__));define('KIRPI_CORE_ENTRY',true);require BASE_PATH.'/core/config.php';require BASE_PATH.'/core/database.php';require BASE_PATH.'/core/functions.php';require BASE_PATH.'/modules/governance/helpers.php';
$failures=[];$assert=static function(bool $condition,string $message)use(&$failures):void{if(!$condition)$failures[]=$message;};
$manifest=json_decode((string)file_get_contents(BASE_PATH.'/modules/governance/module.json'),true);$assert(($manifest['key']??null)==='governance','Governance manifest key is invalid.');$assert(($manifest['requires'][0]??null)==='organization','Governance must depend on organization.');
foreach(['governance_ownership_assignments','governance_delegations'] as $table)$assert(db_table_exists($table),"Missing governance table: {$table}");
$permissions=db()->query("SELECT slug FROM permissions WHERE slug LIKE 'governance.%'")->fetchAll(PDO::FETCH_COLUMN);foreach(['governance.view','governance.ownership.manage','governance.raci.manage','governance.approval.manage','governance.delegation.manage'] as $permission)$assert(in_array($permission,$permissions,true),"Missing permission: {$permission}");
$routes=require BASE_PATH.'/modules/governance/routes.php';foreach(['governance/view','ajax/governance/datatable','ajax/governance/form','governance/actions/save','governance/actions/revoke'] as $route)$assert(isset($routes[$route]),"Missing route: {$route}");
$assert(governance_effective_status(['status'=>'active','starts_on'=>date('Y-m-d',strtotime('-2 days')),'ends_on'=>date('Y-m-d',strtotime('-1 day'))])==='expired','Past delegation must expire.');$assert(governance_effective_status(['status'=>'active','starts_on'=>date('Y-m-d',strtotime('+1 day')),'ends_on'=>date('Y-m-d',strtotime('+2 days'))])==='inactive','Future delegation must be inactive.');
$script=(string)file_get_contents(BASE_PATH.'/modules/governance/scripts/view.js');$assert(str_contains($script,'syncCompanyUsers'),'Governance user fields must be filtered by company.');$form=(string)file_get_contents(BASE_PATH.'/modules/governance/modals/form.php');$assert(str_contains($form,'data-company-ids'),'Governance user options must carry company scope metadata.');
$sync=kirpi_ai_sync_schema_registry_from_manifests();$assert(in_array(($sync['status']??''),['success','partial'],true),'AI schema sync failed.');$entities=db()->query("SELECT entity_key FROM ai_schema_entities WHERE module_key='governance'")->fetchAll(PDO::FETCH_COLUMN);foreach(['ownership_assignment','delegation'] as $entity)$assert(in_array($entity,$entities,true),"Missing AI entity: {$entity}");
if($failures){foreach($failures as $failure)fwrite(STDERR,"FAIL: {$failure}\n");exit(1);}fwrite(STDOUT,"Governance foundation: PASS\n");
