<?php
require_once BASE_PATH.'/modules/organization/helpers.php';

function qms_entities_uuid(): string {
 $b=random_bytes(16);$b[6]=chr((ord($b[6])&0x0f)|0x40);$b[8]=chr((ord($b[8])&0x3f)|0x80);$h=bin2hex($b);return substr($h,0,8).'-'.substr($h,8,4).'-'.substr($h,12,4).'-'.substr($h,16,4).'-'.substr($h,20);
}
function qms_entities_allowed_statuses(): array { return ['draft','active','pending_approval','rejected','closed','cancelled','superseded','archived']; }
function qms_entities_type(string $entityType): ?array { $s=db()->prepare("SELECT * FROM qms_entity_types WHERE entity_type=:type AND status='active'");$s->execute([':type'=>$entityType]);return $s->fetch(PDO::FETCH_ASSOC)?:null; }
function qms_entities_next_code(int $companyId,string $entityType,?int $facilityId=null,?int $year=null): string {
 $own=!db()->inTransaction();if($own)db()->beginTransaction();try{
  $type=qms_entities_type($entityType);if(!$type||!(int)$type['is_numbered']||trim((string)$type['entity_prefix'])==='')throw new InvalidArgumentException('Entity type is not numbered.');
  $company=db()->prepare('SELECT company_code FROM organization_companies WHERE id=:id');$company->execute([':id'=>$companyId]);$companyCode=(string)$company->fetchColumn();if($companyCode==='')throw new InvalidArgumentException('Invalid company.');
  if($facilityId&& !organization_record_belongs_to_company('organization_units',$facilityId,$companyId))throw new InvalidArgumentException('Invalid facility scope.');
  $period=(string)($year??(int)date('Y'));$insert=db()->prepare("INSERT INTO qms_number_sequences(company_id,facility_id,entity_type,period_key) VALUES(:company,:facility,:type,:period) ON DUPLICATE KEY UPDATE updated_at=updated_at");$insert->execute([':company'=>$companyId,':facility'=>$facilityId?:null,':type'=>$entityType,':period'=>$period]);
  $select=db()->prepare('SELECT id,template,last_sequence FROM qms_number_sequences WHERE company_id=:company AND facility_scope_key=:facility_key AND entity_type=:type AND period_key=:period FOR UPDATE');$select->execute([':company'=>$companyId,':facility_key'=>$facilityId?:0,':type'=>$entityType,':period'=>$period]);$sequence=$select->fetch(PDO::FETCH_ASSOC);if(!$sequence)throw new RuntimeException('Sequence row missing.');
  $next=(int)$sequence['last_sequence']+1;$update=db()->prepare('UPDATE qms_number_sequences SET last_sequence=:next WHERE id=:id');$update->execute([':next'=>$next,':id'=>$sequence['id']]);$padded=str_pad((string)$next,5,'0',STR_PAD_LEFT);$code=strtr((string)$sequence['template'],['{company_code}'=>$companyCode,'{entity_prefix}'=>(string)$type['entity_prefix'],'{year}'=>$period,'{sequence:5}'=>$padded,'{sequence}'=>(string)$next]);if($own)db()->commit();return $code;
 }catch(Throwable $e){if($own&&db()->inTransaction())db()->rollBack();throw $e;}
}
function qms_entities_register(array $data): array {
 $company=(int)($data['company_id']??0);$typeKey=trim((string)($data['entity_type']??''));$domainTable=trim((string)($data['domain_table']??''));$domainId=(int)($data['domain_record_id']??0);$title=trim((string)($data['title']??''));$status=(string)($data['status']??'draft');
 if($company<=0||$typeKey===''||$domainTable===''||$domainId<=0||$title===''||!in_array($status,qms_entities_allowed_statuses(),true))throw new InvalidArgumentException('Invalid managed entity data.');$type=qms_entities_type($typeKey);if(!$type)throw new InvalidArgumentException('Invalid entity type.');
 $own=!db()->inTransaction();if($own)db()->beginTransaction();try{$code=trim((string)($data['entity_code']??''));if($code===''&&(int)$type['is_numbered'])$code=qms_entities_next_code($company,$typeKey,(int)($data['facility_id']??0)?:null);if($code==='')throw new InvalidArgumentException('Entity code is required.');
  $user=(int)($data['actor_user_id']??(current_user()['id']??0));$metadata=$data['metadata']??null;$stmt=db()->prepare('INSERT INTO qms_entities(entity_uid,entity_type,domain_table,domain_record_id,entity_code,title,description,company_id,facility_id,department_id,team_id,owner_user_id,status,retention_class,metadata,created_by_user_id,updated_by_user_id) VALUES(:uid,:type,:domain_table,:domain_id,:code,:title,:description,:company,:facility,:department,:team,:owner,:status,:retention,:metadata,:created_user,:updated_user)');$stmt->execute([':uid'=>qms_entities_uuid(),':type'=>$typeKey,':domain_table'=>$domainTable,':domain_id'=>$domainId,':code'=>$code,':title'=>$title,':description'=>trim((string)($data['description']??''))?:null,':company'=>$company,':facility'=>(int)($data['facility_id']??0)?:null,':department'=>(int)($data['department_id']??0)?:null,':team'=>(int)($data['team_id']??0)?:null,':owner'=>(int)($data['owner_user_id']??0)?:null,':status'=>$status,':retention'=>(string)($data['retention_class']??$type['retention_class']),':metadata'=>$metadata===null?null:json_encode($metadata,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES),':created_user'=>$user?:null,':updated_user'=>$user?:null]);$id=(int)db()->lastInsertId();if($own)db()->commit();return qms_entities_row($id)??[];
 }catch(Throwable $e){if($own&&db()->inTransaction())db()->rollBack();throw $e;}
}
function qms_entities_row(int $id): ?array { $s=db()->prepare('SELECT x.*,c.company_name,u.name AS owner_name,t.display_name AS entity_type_name FROM qms_entities x JOIN organization_companies c ON c.id=x.company_id JOIN qms_entity_types t ON t.entity_type=x.entity_type LEFT JOIN users u ON u.id=x.owner_user_id WHERE x.id=:id');$s->execute([':id'=>$id]);$r=$s->fetch(PDO::FETCH_ASSOC);if(!$r)return null;$r['row_key']='entities-'.$id;return $r; }
