CREATE TABLE IF NOT EXISTS governance_ownership_assignments (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    company_id BIGINT UNSIGNED NOT NULL,
    subject_type VARCHAR(50) NOT NULL,
    subject_id BIGINT UNSIGNED NOT NULL,
    subject_title VARCHAR(190) NOT NULL,
    ownership_type VARCHAR(50) NOT NULL,
    owner_user_id INT NOT NULL,
    starts_on DATE NULL,
    ends_on DATE NULL,
    status VARCHAR(30) NOT NULL DEFAULT 'active',
    notes TEXT NULL,
    created_by_user_id INT NULL,
    updated_by_user_id INT NULL,
    created_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY uk_governance_ownership_subject_type_owner (company_id, subject_type, subject_id, ownership_type, owner_user_id),
    INDEX idx_governance_ownership_company_status (company_id, status),
    INDEX idx_governance_ownership_owner (owner_user_id, status),
    CONSTRAINT fk_governance_ownership_company FOREIGN KEY (company_id) REFERENCES organization_companies(id) ON DELETE RESTRICT,
    CONSTRAINT fk_governance_ownership_owner FOREIGN KEY (owner_user_id) REFERENCES users(id) ON DELETE RESTRICT,
    CONSTRAINT fk_governance_ownership_created_by FOREIGN KEY (created_by_user_id) REFERENCES users(id) ON DELETE SET NULL,
    CONSTRAINT fk_governance_ownership_updated_by FOREIGN KEY (updated_by_user_id) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS governance_delegations (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    company_id BIGINT UNSIGNED NOT NULL,
    ownership_assignment_id BIGINT UNSIGNED NULL,
    from_user_id INT NOT NULL,
    to_user_id INT NOT NULL,
    starts_on DATE NOT NULL,
    ends_on DATE NOT NULL,
    reason VARCHAR(500) NOT NULL,
    status VARCHAR(30) NOT NULL DEFAULT 'active',
    revoked_at DATETIME NULL,
    revoked_by_user_id INT NULL,
    created_by_user_id INT NULL,
    updated_by_user_id INT NULL,
    created_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX idx_governance_delegations_company_status (company_id, status),
    INDEX idx_governance_delegations_users_dates (from_user_id, to_user_id, starts_on, ends_on),
    CONSTRAINT fk_governance_delegation_company FOREIGN KEY (company_id) REFERENCES organization_companies(id) ON DELETE RESTRICT,
    CONSTRAINT fk_governance_delegation_ownership FOREIGN KEY (ownership_assignment_id) REFERENCES governance_ownership_assignments(id) ON DELETE RESTRICT,
    CONSTRAINT fk_governance_delegation_from_user FOREIGN KEY (from_user_id) REFERENCES users(id) ON DELETE RESTRICT,
    CONSTRAINT fk_governance_delegation_to_user FOREIGN KEY (to_user_id) REFERENCES users(id) ON DELETE RESTRICT,
    CONSTRAINT fk_governance_delegation_revoked_by FOREIGN KEY (revoked_by_user_id) REFERENCES users(id) ON DELETE SET NULL,
    CONSTRAINT fk_governance_delegation_created_by FOREIGN KEY (created_by_user_id) REFERENCES users(id) ON DELETE SET NULL,
    CONSTRAINT fk_governance_delegation_updated_by FOREIGN KEY (updated_by_user_id) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
