<?php
if (!defined('KIRPI_CORE_ENTRY')) exit;
require_once BASE_PATH . '/modules/governance/helpers.php'; require_once BASE_PATH . '/core/kirpi_table.php';
$resource=trim((string)($_GET['resource']??''));if(!governance_resource_config($resource))json_response(['error'=>'invalid resource'],422);
$request=kirpi_table_request();$params=[];$where=[];$scope=organization_scope_where('x.company_id',$params);if($scope!==null)$where[]=$scope;
if($resource==='ownerships'){$from='governance_ownership_assignments x JOIN organization_companies c ON c.id=x.company_id JOIN users u ON u.id=x.owner_user_id';$select='x.*,c.company_name,u.name AS owner_name';$search=['c.company_name','x.subject_type','x.subject_title','x.ownership_type','u.name'];$columns=['company_name'=>'c.company_name','subject_type'=>'x.subject_type','subject_title'=>'x.subject_title','ownership_type'=>'x.ownership_type','owner_name'=>'u.name','starts_on'=>'x.starts_on','ends_on'=>'x.ends_on','status'=>'x.status'];$fallback='x.id DESC';}
else{$from='governance_delegations x JOIN organization_companies c ON c.id=x.company_id JOIN users fu ON fu.id=x.from_user_id JOIN users tu ON tu.id=x.to_user_id';$select='x.*,c.company_name,fu.name AS from_user_name,tu.name AS to_user_name';$search=['c.company_name','fu.name','tu.name','x.reason'];$columns=['company_name'=>'c.company_name','from_user_name'=>'fu.name','to_user_name'=>'tu.name','starts_on'=>'x.starts_on','ends_on'=>'x.ends_on','status'=>'x.status'];$fallback='x.id DESC';}
$global=trim((string)$request['search']);if($global!==''){$parts=[];foreach($search as $i=>$column){$key=':search_'.$i;$parts[]="$column LIKE $key";$params[$key]='%'.$global.'%';}$where[]='('.implode(' OR ',$parts).')';}
$columnSearches=kirpi_table_column_searches($request);foreach($columnSearches as $name=>$value){if(!isset($columns[$name]))continue;$key=':column_'.preg_replace('/[^a-z0-9_]/i','',$name);$where[]=$columns[$name]." LIKE $key";$params[$key]='%'.$value.'%';}
$totalParams=[];$totalWhere=organization_scope_where('x.company_id',$totalParams);$totalSql='SELECT COUNT(*) FROM '.$from.($totalWhere!==null?' WHERE '.$totalWhere:'');$totalStmt=db()->prepare($totalSql);$totalStmt->execute($totalParams);$total=(int)$totalStmt->fetchColumn();
$filteredSql='SELECT COUNT(*) FROM '.$from.($where?' WHERE '.implode(' AND ',$where):'');$filteredStmt=db()->prepare($filteredSql);kirpi_table_bind($filteredStmt,$params);$filteredStmt->execute();$filtered=(int)$filteredStmt->fetchColumn();
$order=kirpi_table_order_sql($request,$columns,$fallback);$sql='SELECT '.$select.' FROM '.$from.($where?' WHERE '.implode(' AND ',$where):'').' ORDER BY '.$order.' LIMIT :length OFFSET :start';$stmt=db()->prepare($sql);kirpi_table_bind($stmt,$params);$stmt->bindValue(':length',(int)$request['length'],PDO::PARAM_INT);$stmt->bindValue(':start',(int)$request['start'],PDO::PARAM_INT);$stmt->execute();$rows=$stmt->fetchAll(PDO::FETCH_ASSOC)?:[];foreach($rows as &$row){$row['status']=governance_effective_status($row);$row['row_key']=$resource.'-'.$row['id'];}unset($row);kirpi_table_response($request,$total,$filtered,$rows);
