<?php
if (!defined('KIRPI_CORE_ENTRY')) exit;
require_once BASE_PATH . '/modules/governance/language.php'; require_once BASE_PATH . '/modules/governance/helpers.php'; require_action('POST',true);
if(!verify_csrf_token($_POST['csrf_token']??null))json_response(['status'=>'error','message'=>'CSRF'],419);
$resource=trim((string)($_POST['resource']??''));$id=(int)($_POST['id']??0);$config=governance_resource_config($resource);
if(!$config)json_response(['status'=>'error','message'=>governance_lang('invalid_resource')],422);if(!check_permission($config['permission']))json_response(['status'=>'error','message'=>governance_lang('permission_denied')],403);
$company=(int)($_POST['company_id']??0);if(!organization_company_in_scope($company))json_response(['status'=>'error','message'=>governance_lang('permission_denied')],403);
$starts=trim((string)($_POST['starts_on']??''));$ends=trim((string)($_POST['ends_on']??''));if(!governance_valid_date($starts)||!governance_valid_date($ends)||($starts&&$ends&&$ends<$starts))json_response(['status'=>'error','message'=>governance_lang('invalid_date_range')],422);
$userId=(int)(current_user()['id']??0);
try{db()->beginTransaction();
if($resource==='ownerships'){$subjectType=trim((string)($_POST['subject_type']??''));$subjectId=(int)($_POST['subject_id']??0);$title=trim((string)($_POST['subject_title']??''));$ownershipType=trim((string)($_POST['ownership_type']??''));$owner=(int)($_POST['owner_user_id']??0);if(!in_array($subjectType,governance_subject_types(),true)||$subjectId<=0||$title===''||!in_array($ownershipType,governance_ownership_types(),true)||!governance_user_in_company($owner,$company))throw new InvalidArgumentException(governance_lang('required_fields'));$data=[':company'=>$company,':subject_type'=>$subjectType,':subject_id'=>$subjectId,':title'=>$title,':ownership_type'=>$ownershipType,':owner'=>$owner,':starts'=>$starts?:null,':ends'=>$ends?:null,':notes'=>trim((string)($_POST['reason']??''))?:null,':user'=>$userId];if($id){$data[':id']=$id;$sql='UPDATE governance_ownership_assignments SET company_id=:company,subject_type=:subject_type,subject_id=:subject_id,subject_title=:title,ownership_type=:ownership_type,owner_user_id=:owner,starts_on=:starts,ends_on=:ends,notes=:notes,updated_by_user_id=:user WHERE id=:id';}else{unset($data[':user']);$data[':created_user']=$userId;$data[':updated_user']=$userId;$sql='INSERT INTO governance_ownership_assignments(company_id,subject_type,subject_id,subject_title,ownership_type,owner_user_id,starts_on,ends_on,notes,created_by_user_id,updated_by_user_id) VALUES(:company,:subject_type,:subject_id,:title,:ownership_type,:owner,:starts,:ends,:notes,:created_user,:updated_user)';}}
else{$from=(int)($_POST['from_user_id']??0);$to=(int)($_POST['to_user_id']??0);$reason=trim((string)($_POST['reason']??''));if($from<=0||$to<=0||$starts===''||$ends===''||$reason===''||!governance_user_in_company($from,$company)||!governance_user_in_company($to,$company))throw new InvalidArgumentException(governance_lang('required_fields'));if($from===$to)throw new InvalidArgumentException(governance_lang('same_delegate'));$data=[':company'=>$company,':from_user'=>$from,':to_user'=>$to,':starts'=>$starts,':ends'=>$ends,':reason'=>$reason,':user'=>$userId];if($id){$data[':id']=$id;$sql="UPDATE governance_delegations SET company_id=:company,from_user_id=:from_user,to_user_id=:to_user,starts_on=:starts,ends_on=:ends,reason=:reason,updated_by_user_id=:user WHERE id=:id AND status<>'revoked'";}else{unset($data[':user']);$data[':created_user']=$userId;$data[':updated_user']=$userId;$sql='INSERT INTO governance_delegations(company_id,from_user_id,to_user_id,starts_on,ends_on,reason,created_by_user_id,updated_by_user_id) VALUES(:company,:from_user,:to_user,:starts,:ends,:reason,:created_user,:updated_user)';}}
$stmt=db()->prepare($sql);$stmt->execute($data);$recordId=$id?:((int)db()->lastInsertId());kirpi_audit_log($id?'update':'create','governance',['resource'=>$resource],$config['entity'],$recordId,'success');db()->commit();json_response(['status'=>'success','message'=>governance_lang($id?'updated_success':'created_success'),'data'=>['resource'=>$resource,'row'=>governance_resource_row($resource,$recordId)]]);
}catch(InvalidArgumentException $e){if(db()->inTransaction())db()->rollBack();json_response(['status'=>'error','message'=>$e->getMessage()],422);}catch(Throwable $e){if(db()->inTransaction())db()->rollBack();error_log('governance save error: '.$e->getMessage());json_response(['status'=>'error','message'=>governance_lang('save_error')],500);}
