<?php
if (!defined('KIRPI_CORE_ENTRY')) exit;
require_once BASE_PATH . '/modules/organization/language.php';
require_once BASE_PATH . '/modules/organization/helpers.php';
$resource=trim((string)($_GET['resource']??''));$id=(int)($_GET['id']??0);$config=organization_resource_config($resource);
if(!$config){echo '<div class="modal-body"><div class="alert alert-danger">'.e(organization_lang('invalid_resource')).'</div></div>';exit;}
$permission=$id>0?$config['edit']:$config['create'];if(!check_permission($permission)){echo '<div class="modal-body"><div class="alert alert-danger">'.e(organization_lang('permission_denied')).'</div></div>';exit;}
$record=[];if($id>0){$stmt=db()->prepare("SELECT * FROM {$config['table']} WHERE id=:id");$stmt->execute([':id'=>$id]);$record=$stmt->fetch(PDO::FETCH_ASSOC)?:[];if(!$record){echo '<div class="modal-body"><div class="alert alert-danger">'.e(organization_lang('invalid_record')).'</div></div>';exit;}}
if($record){$recordCompanyId=$resource==='companies'?(int)$record['id']:(int)($record['company_id']??0);if(!organization_company_in_scope($recordCompanyId)){echo '<div class="modal-body"><div class="alert alert-danger">'.e(organization_lang('permission_denied')).'</div></div>';exit;}}
$options=organization_select_options();
$titles=['companies'=>$id?organization_lang('edit_company'):organization_lang('new_company'),'units'=>$id?organization_lang('edit_unit'):organization_lang('new_unit'),'positions'=>$id?organization_lang('edit_position'):organization_lang('new_position'),'assignments'=>$id?organization_lang('edit_assignment'):organization_lang('new_assignment')];
$v=static fn(string $key,string $default='')=>(string)($record[$key]??$default);
?>
<div class="modal-header"><h5 class="modal-title"><?php echo e($titles[$resource]); ?></h5><button type="button" class="btn-close" data-bs-dismiss="modal"></button></div>
<form id="organization-form" action="<?php echo base_url('organization/actions/save'); ?>" method="post" data-ajax="true" data-close-modal="true">
<div class="modal-body"><input type="hidden" name="csrf_token" value="<?php echo e(get_csrf_token()); ?>"><input type="hidden" name="resource" value="<?php echo e($resource); ?>"><input type="hidden" name="id" value="<?php echo $id; ?>"><div class="row g-3">
<?php if($resource==='companies'): ?>
 <div class="col-md-4"><label class="form-label form-required"><?php echo e(organization_lang('company_code')); ?></label><input name="company_code" class="form-control" maxlength="40" value="<?php echo e($v('company_code')); ?>" required><div class="form-hint"><?php echo e(organization_lang('code_hint')); ?></div></div>
 <div class="col-md-8"><label class="form-label form-required"><?php echo e(organization_lang('company_name')); ?></label><input name="company_name" class="form-control" maxlength="190" value="<?php echo e($v('company_name')); ?>" required></div>
 <div class="col-12"><label class="form-label"><?php echo e(organization_lang('legal_name')); ?></label><input name="legal_name" class="form-control" maxlength="190" value="<?php echo e($v('legal_name')); ?>"></div>
 <div class="col-md-6"><label class="form-label"><?php echo e(organization_lang('tax_office')); ?></label><input name="tax_office" class="form-control" value="<?php echo e($v('tax_office')); ?>"></div><div class="col-md-6"><label class="form-label"><?php echo e(organization_lang('tax_number')); ?></label><input name="tax_number" class="form-control" value="<?php echo e($v('tax_number')); ?>"></div>
<?php elseif($resource==='units'): ?>
 <div class="col-md-6"><label class="form-label form-required"><?php echo e(organization_lang('company')); ?></label><select name="company_id" class="form-select js-organization-company" data-organization-company required><option value=""><?php echo e(organization_lang('select_company')); ?></option><?php foreach($options['companies'] as $o):?><option value="<?php echo (int)$o['id']; ?>" <?php echo (int)$v('company_id')===(int)$o['id']?'selected':'';?>><?php echo e($o['company_code'].' - '.$o['company_name']);?></option><?php endforeach;?></select></div>
 <div class="col-md-6"><label class="form-label form-required"><?php echo e(organization_lang('unit_type')); ?></label><select name="unit_type" class="form-select" required><?php foreach(organization_allowed_unit_types() as $type):?><option value="<?php echo e($type);?>" <?php echo $v('unit_type','department')===$type?'selected':'';?>><?php echo e(organization_lang($type));?></option><?php endforeach;?></select></div>
 <div class="col-md-4"><label class="form-label form-required"><?php echo e(organization_lang('unit_code')); ?></label><input name="unit_code" class="form-control" maxlength="40" value="<?php echo e($v('unit_code')); ?>" required></div><div class="col-md-8"><label class="form-label form-required"><?php echo e(organization_lang('unit_name')); ?></label><input name="unit_name" class="form-control" value="<?php echo e($v('unit_name')); ?>" required></div>
 <div class="col-md-9"><label class="form-label"><?php echo e(organization_lang('parent_unit')); ?></label><select name="parent_unit_id" class="form-select" data-company-filter><option value=""><?php echo e(organization_lang('no_parent')); ?></option><?php foreach($options['units'] as $o):if((int)$o['id']===$id)continue;?><option value="<?php echo (int)$o['id'];?>" data-company-id="<?php echo (int)$o['company_id'];?>" <?php echo (int)$v('parent_unit_id')===(int)$o['id']?'selected':'';?>><?php echo e($o['unit_code'].' - '.$o['unit_name']);?></option><?php endforeach;?></select></div><div class="col-md-3"><label class="form-label"><?php echo e(organization_lang('sort_order')); ?></label><input type="number" name="sort_order" class="form-control" value="<?php echo e($v('sort_order','100')); ?>"></div>
 <div class="col-12"><label class="form-label"><?php echo e(organization_lang('description')); ?></label><textarea name="description" class="form-control" rows="3"><?php echo e($v('description')); ?></textarea></div>
<?php elseif($resource==='positions'): ?>
 <div class="col-md-6"><label class="form-label form-required"><?php echo e(organization_lang('company')); ?></label><select name="company_id" class="form-select" data-organization-company required><option value=""><?php echo e(organization_lang('select_company')); ?></option><?php foreach($options['companies'] as $o):?><option value="<?php echo (int)$o['id'];?>" <?php echo (int)$v('company_id')===(int)$o['id']?'selected':'';?>><?php echo e($o['company_name']);?></option><?php endforeach;?></select></div><div class="col-md-6"><label class="form-label"><?php echo e(organization_lang('department')); ?></label><select name="department_unit_id" class="form-select" data-company-filter><option value=""><?php echo e(organization_lang('none')); ?></option><?php foreach($options['units'] as $o):if($o['unit_type']!=='department')continue;?><option value="<?php echo (int)$o['id'];?>" data-company-id="<?php echo (int)$o['company_id'];?>" <?php echo (int)$v('department_unit_id')===(int)$o['id']?'selected':'';?>><?php echo e($o['unit_name']);?></option><?php endforeach;?></select></div>
 <div class="col-md-4"><label class="form-label form-required"><?php echo e(organization_lang('position_code')); ?></label><input name="position_code" class="form-control" value="<?php echo e($v('position_code')); ?>" required></div><div class="col-md-8"><label class="form-label form-required"><?php echo e(organization_lang('position_name')); ?></label><input name="position_name" class="form-control" value="<?php echo e($v('position_name')); ?>" required></div><div class="col-12"><label class="form-label"><?php echo e(organization_lang('description')); ?></label><textarea name="description" class="form-control" rows="3"><?php echo e($v('description')); ?></textarea></div>
<?php else: ?>
 <div class="col-md-6"><label class="form-label form-required"><?php echo e(organization_lang('user')); ?></label><select name="user_id" class="form-select" required><option value=""><?php echo e(organization_lang('select_user')); ?></option><?php foreach($options['users'] as $o):?><option value="<?php echo (int)$o['id'];?>" <?php echo (int)$v('user_id')===(int)$o['id']?'selected':'';?>><?php echo e($o['name'].' ('.$o['email'].')');?></option><?php endforeach;?></select></div><div class="col-md-6"><label class="form-label form-required"><?php echo e(organization_lang('company')); ?></label><select name="company_id" class="form-select" data-organization-company required><option value=""><?php echo e(organization_lang('select_company')); ?></option><?php foreach($options['companies'] as $o):?><option value="<?php echo (int)$o['id'];?>" <?php echo (int)$v('company_id')===(int)$o['id']?'selected':'';?>><?php echo e($o['company_name']);?></option><?php endforeach;?></select></div>
 <div class="col-md-6"><label class="form-label"><?php echo e(organization_lang('unit')); ?></label><select name="unit_id" class="form-select" data-company-filter><option value=""><?php echo e(organization_lang('select_unit')); ?></option><?php foreach($options['units'] as $o):?><option value="<?php echo (int)$o['id'];?>" data-company-id="<?php echo (int)$o['company_id'];?>" <?php echo (int)$v('unit_id')===(int)$o['id']?'selected':'';?>><?php echo e($o['unit_name']);?></option><?php endforeach;?></select></div><div class="col-md-6"><label class="form-label"><?php echo e(organization_lang('position')); ?></label><select name="position_id" class="form-select" data-company-filter><option value=""><?php echo e(organization_lang('select_position')); ?></option><?php foreach($options['positions'] as $o):?><option value="<?php echo (int)$o['id'];?>" data-company-id="<?php echo (int)$o['company_id'];?>" <?php echo (int)$v('position_id')===(int)$o['id']?'selected':'';?>><?php echo e($o['position_name']);?></option><?php endforeach;?></select></div>
 <div class="col-md-6"><label class="form-label form-required"><?php echo e(organization_lang('scope_mode')); ?></label><select name="scope_mode" class="form-select" required><?php foreach(organization_allowed_scope_modes() as $mode):?><option value="<?php echo e($mode);?>" <?php echo $v('scope_mode','self')===$mode?'selected':'';?>><?php echo e(organization_lang('scope_'.$mode));?></option><?php endforeach;?></select></div><div class="col-md-6 d-flex align-items-end"><label class="form-check form-switch"><input type="checkbox" name="is_primary" value="1" class="form-check-input" <?php echo (int)$v('is_primary','0')===1?'checked':'';?>><span class="form-check-label"><?php echo e(organization_lang('is_primary')); ?></span></label></div>
 <div class="col-md-6"><label class="form-label"><?php echo e(organization_lang('starts_at')); ?></label><input type="date" name="starts_at" class="form-control" value="<?php echo e($v('starts_at')?date('Y-m-d',strtotime($v('starts_at'))):'');?>"></div><div class="col-md-6"><label class="form-label"><?php echo e(organization_lang('ends_at')); ?></label><input type="date" name="ends_at" class="form-control" value="<?php echo e($v('ends_at')?date('Y-m-d',strtotime($v('ends_at'))):'');?>"></div><div class="col-12"><label class="form-label"><?php echo e(organization_lang('assignment_reason')); ?></label><input name="assignment_reason" class="form-control" value="<?php echo e($v('assignment_reason')); ?>"></div>
<?php endif; ?>
<?php if($resource!=='assignments'):?><div class="col-12"><label class="form-check form-switch"><input type="checkbox" name="is_active" value="1" class="form-check-input" <?php echo $id===0||$v('status','active')==='active'?'checked':'';?>><span class="form-check-label"><?php echo e(organization_lang('active')); ?></span></label></div><?php endif;?>
</div></div><div class="modal-footer"><button type="button" class="btn me-auto" data-bs-dismiss="modal"><?php echo e(organization_lang('cancel')); ?></button><button type="submit" class="btn btn-primary"><?php echo e($id?organization_lang('update'):organization_lang('save')); ?></button></div></form>
