CREATE TABLE IF NOT EXISTS qms_entity_types (
 entity_type VARCHAR(80) PRIMARY KEY, owner_module VARCHAR(80) NOT NULL, display_name VARCHAR(160) NOT NULL, entity_prefix VARCHAR(20) NULL, retention_class VARCHAR(30) NOT NULL DEFAULT 'operational', is_numbered TINYINT(1) NOT NULL DEFAULT 0, status VARCHAR(30) NOT NULL DEFAULT 'active', created_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
 INDEX idx_qms_entity_types_module_status (owner_module,status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS qms_entities (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, entity_uid CHAR(36) NOT NULL, entity_type VARCHAR(80) NOT NULL, domain_table VARCHAR(120) NOT NULL, domain_record_id BIGINT UNSIGNED NOT NULL, entity_code VARCHAR(100) NOT NULL, title VARCHAR(190) NOT NULL, description TEXT NULL,
 company_id BIGINT UNSIGNED NOT NULL, facility_id BIGINT UNSIGNED NULL, department_id BIGINT UNSIGNED NULL, team_id BIGINT UNSIGNED NULL, owner_user_id INT NULL, status VARCHAR(40) NOT NULL DEFAULT 'draft', retention_class VARCHAR(30) NOT NULL DEFAULT 'operational', metadata JSON NULL,
 closed_at DATETIME NULL, closed_by_user_id INT NULL, archived_at DATETIME NULL, archived_by_user_id INT NULL, created_by_user_id INT NULL, updated_by_user_id INT NULL, created_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
 UNIQUE KEY uk_qms_entities_uid (entity_uid), UNIQUE KEY uk_qms_entities_domain (domain_table,domain_record_id), UNIQUE KEY uk_qms_entities_company_code (company_id,entity_code), INDEX idx_qms_entities_type_status (entity_type,status), INDEX idx_qms_entities_company_status (company_id,status),
 CONSTRAINT fk_qms_entities_type FOREIGN KEY (entity_type) REFERENCES qms_entity_types(entity_type) ON DELETE RESTRICT, CONSTRAINT fk_qms_entities_company FOREIGN KEY (company_id) REFERENCES organization_companies(id) ON DELETE RESTRICT,
 CONSTRAINT fk_qms_entities_facility FOREIGN KEY (facility_id) REFERENCES organization_units(id) ON DELETE RESTRICT, CONSTRAINT fk_qms_entities_department FOREIGN KEY (department_id) REFERENCES organization_units(id) ON DELETE RESTRICT, CONSTRAINT fk_qms_entities_team FOREIGN KEY (team_id) REFERENCES organization_units(id) ON DELETE RESTRICT,
 CONSTRAINT fk_qms_entities_owner FOREIGN KEY (owner_user_id) REFERENCES users(id) ON DELETE SET NULL, CONSTRAINT fk_qms_entities_closed_by FOREIGN KEY (closed_by_user_id) REFERENCES users(id) ON DELETE SET NULL, CONSTRAINT fk_qms_entities_archived_by FOREIGN KEY (archived_by_user_id) REFERENCES users(id) ON DELETE SET NULL, CONSTRAINT fk_qms_entities_created_by FOREIGN KEY (created_by_user_id) REFERENCES users(id) ON DELETE SET NULL, CONSTRAINT fk_qms_entities_updated_by FOREIGN KEY (updated_by_user_id) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS qms_number_sequences (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, company_id BIGINT UNSIGNED NOT NULL, facility_id BIGINT UNSIGNED NULL, facility_scope_key BIGINT UNSIGNED GENERATED ALWAYS AS (IFNULL(facility_id,0)) STORED, entity_type VARCHAR(80) NOT NULL, period_key VARCHAR(20) NOT NULL, template VARCHAR(190) NOT NULL DEFAULT '{company_code}-{entity_prefix}-{year}-{sequence:5}', last_sequence BIGINT UNSIGNED NOT NULL DEFAULT 0, created_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
 UNIQUE KEY uk_qms_number_sequence_scope (company_id,facility_scope_key,entity_type,period_key), CONSTRAINT fk_qms_number_sequence_company FOREIGN KEY (company_id) REFERENCES organization_companies(id) ON DELETE RESTRICT, CONSTRAINT fk_qms_number_sequence_facility FOREIGN KEY (facility_id) REFERENCES organization_units(id) ON DELETE RESTRICT, CONSTRAINT fk_qms_number_sequence_type FOREIGN KEY (entity_type) REFERENCES qms_entity_types(entity_type) ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

INSERT INTO qms_entity_types(entity_type,owner_module,display_name,entity_prefix,retention_class,is_numbered) VALUES
('process','governance','Process','PRC','operational',1),('standard','standards','Standard','STD','permanent',1),('standard_version','standards','Standard Version',NULL,'permanent',0),('clause','standards','Clause',NULL,'permanent',0),('requirement','standards','Requirement','REQ','permanent',1),('control','standards','Control','CTL','permanent',1),
('controlled_document','controlled_documents','Controlled Document','DOC','regulated',1),('document_revision','controlled_documents','Document Revision',NULL,'regulated',0),('evidence','controlled_documents','Evidence','EVD','regulated',1),('risk','risks','Risk','RSK','operational',1),('nonconformity','nonconformities','Nonconformity','NC','regulated',1),('capa','capa','CAPA','CAPA','regulated',1),('capa_action','capa','CAPA Action',NULL,'regulated',0),('quality_audit','audit_management','Quality Audit','AUD','regulated',1),('audit_finding','audit_management','Audit Finding','FND','regulated',1),('training_record','training','Training Record','TRN','regulated',1),('competency_record','competencies','Competency Record',NULL,'regulated',0),('supplier','suppliers','Supplier','SUP','operational',1),('equipment','equipment','Equipment','EQP','regulated',1),('calibration_record','calibration','Calibration Record','CAL','regulated',1),('compliance_evaluation','compliance','Compliance Evaluation',NULL,'regulated',0),('compliance_gap','compliance','Compliance Gap','GAP','regulated',1)
ON DUPLICATE KEY UPDATE owner_module=VALUES(owner_module),display_name=VALUES(display_name),entity_prefix=VALUES(entity_prefix),retention_class=VALUES(retention_class),is_numbered=VALUES(is_numbered);
