CREATE TABLE IF NOT EXISTS qms_domain_events (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    event_id CHAR(36) NOT NULL,
    event_type VARCHAR(120) NOT NULL,
    entity_type VARCHAR(80) NOT NULL,
    entity_id BIGINT UNSIGNED NOT NULL,
    company_id BIGINT UNSIGNED NOT NULL,
    facility_id BIGINT UNSIGNED NULL,
    department_id BIGINT UNSIGNED NULL,
    actor_type VARCHAR(30) NOT NULL,
    actor_user_id INT NULL,
    correlation_id CHAR(36) NOT NULL,
    causation_id CHAR(36) NULL,
    payload_version INT UNSIGNED NOT NULL DEFAULT 1,
    payload JSON NOT NULL,
    metadata JSON NULL,
    source_module VARCHAR(80) NOT NULL,
    request_id VARCHAR(120) NULL,
    occurred_at DATETIME NOT NULL,
    recorded_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE KEY uk_qms_domain_events_event_id (event_id),
    INDEX idx_qms_domain_events_company_recorded (company_id, recorded_at),
    INDEX idx_qms_domain_events_entity (entity_type, entity_id, recorded_at),
    INDEX idx_qms_domain_events_type (event_type, recorded_at),
    INDEX idx_qms_domain_events_correlation (correlation_id),
    CONSTRAINT fk_qms_domain_events_company FOREIGN KEY (company_id) REFERENCES organization_companies(id) ON DELETE RESTRICT,
    CONSTRAINT fk_qms_domain_events_facility FOREIGN KEY (facility_id) REFERENCES organization_units(id) ON DELETE SET NULL,
    CONSTRAINT fk_qms_domain_events_department FOREIGN KEY (department_id) REFERENCES organization_units(id) ON DELETE SET NULL,
    CONSTRAINT fk_qms_domain_events_actor_user FOREIGN KEY (actor_user_id) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
