CREATE TABLE IF NOT EXISTS organization_companies (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    company_code VARCHAR(40) NOT NULL,
    company_name VARCHAR(190) NOT NULL,
    legal_name VARCHAR(190) NULL,
    tax_office VARCHAR(120) NULL,
    tax_number VARCHAR(80) NULL,
    status VARCHAR(30) NOT NULL DEFAULT 'active',
    created_by_user_id INT NULL,
    updated_by_user_id INT NULL,
    archived_at DATETIME NULL,
    archived_by_user_id INT NULL,
    created_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY uk_organization_companies_code (company_code),
    INDEX idx_organization_companies_status (status),
    CONSTRAINT fk_organization_companies_created_by FOREIGN KEY (created_by_user_id) REFERENCES users(id) ON DELETE SET NULL,
    CONSTRAINT fk_organization_companies_updated_by FOREIGN KEY (updated_by_user_id) REFERENCES users(id) ON DELETE SET NULL,
    CONSTRAINT fk_organization_companies_archived_by FOREIGN KEY (archived_by_user_id) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS organization_units (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    company_id BIGINT UNSIGNED NOT NULL,
    parent_unit_id BIGINT UNSIGNED NULL,
    unit_type VARCHAR(30) NOT NULL,
    unit_code VARCHAR(40) NOT NULL,
    unit_name VARCHAR(190) NOT NULL,
    description TEXT NULL,
    status VARCHAR(30) NOT NULL DEFAULT 'active',
    sort_order INT NOT NULL DEFAULT 100,
    created_by_user_id INT NULL,
    updated_by_user_id INT NULL,
    archived_at DATETIME NULL,
    archived_by_user_id INT NULL,
    created_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY uk_organization_units_company_code (company_id, unit_code),
    INDEX idx_organization_units_parent (parent_unit_id),
    INDEX idx_organization_units_company_type_status (company_id, unit_type, status),
    CONSTRAINT fk_organization_units_company FOREIGN KEY (company_id) REFERENCES organization_companies(id) ON DELETE RESTRICT,
    CONSTRAINT fk_organization_units_parent FOREIGN KEY (parent_unit_id) REFERENCES organization_units(id) ON DELETE RESTRICT,
    CONSTRAINT fk_organization_units_created_by FOREIGN KEY (created_by_user_id) REFERENCES users(id) ON DELETE SET NULL,
    CONSTRAINT fk_organization_units_updated_by FOREIGN KEY (updated_by_user_id) REFERENCES users(id) ON DELETE SET NULL,
    CONSTRAINT fk_organization_units_archived_by FOREIGN KEY (archived_by_user_id) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS organization_positions (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    company_id BIGINT UNSIGNED NOT NULL,
    department_unit_id BIGINT UNSIGNED NULL,
    position_code VARCHAR(40) NOT NULL,
    position_name VARCHAR(190) NOT NULL,
    description TEXT NULL,
    status VARCHAR(30) NOT NULL DEFAULT 'active',
    created_by_user_id INT NULL,
    updated_by_user_id INT NULL,
    archived_at DATETIME NULL,
    archived_by_user_id INT NULL,
    created_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY uk_organization_positions_company_code (company_id, position_code),
    INDEX idx_organization_positions_department (department_unit_id),
    INDEX idx_organization_positions_company_status (company_id, status),
    CONSTRAINT fk_organization_positions_company FOREIGN KEY (company_id) REFERENCES organization_companies(id) ON DELETE RESTRICT,
    CONSTRAINT fk_organization_positions_department FOREIGN KEY (department_unit_id) REFERENCES organization_units(id) ON DELETE RESTRICT,
    CONSTRAINT fk_organization_positions_created_by FOREIGN KEY (created_by_user_id) REFERENCES users(id) ON DELETE SET NULL,
    CONSTRAINT fk_organization_positions_updated_by FOREIGN KEY (updated_by_user_id) REFERENCES users(id) ON DELETE SET NULL,
    CONSTRAINT fk_organization_positions_archived_by FOREIGN KEY (archived_by_user_id) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS organization_user_assignments (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    user_id INT NOT NULL,
    company_id BIGINT UNSIGNED NOT NULL,
    unit_id BIGINT UNSIGNED NULL,
    position_id BIGINT UNSIGNED NULL,
    scope_mode VARCHAR(40) NOT NULL DEFAULT 'self',
    is_primary TINYINT(1) NOT NULL DEFAULT 0,
    status VARCHAR(30) NOT NULL DEFAULT 'active',
    starts_at DATETIME NULL,
    ends_at DATETIME NULL,
    assignment_reason VARCHAR(255) NULL,
    created_by_user_id INT NULL,
    updated_by_user_id INT NULL,
    created_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX idx_organization_assignments_user_status (user_id, status),
    INDEX idx_organization_assignments_company_unit (company_id, unit_id),
    INDEX idx_organization_assignments_dates (starts_at, ends_at),
    CONSTRAINT fk_organization_assignments_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    CONSTRAINT fk_organization_assignments_company FOREIGN KEY (company_id) REFERENCES organization_companies(id) ON DELETE RESTRICT,
    CONSTRAINT fk_organization_assignments_unit FOREIGN KEY (unit_id) REFERENCES organization_units(id) ON DELETE RESTRICT,
    CONSTRAINT fk_organization_assignments_position FOREIGN KEY (position_id) REFERENCES organization_positions(id) ON DELETE RESTRICT,
    CONSTRAINT fk_organization_assignments_created_by FOREIGN KEY (created_by_user_id) REFERENCES users(id) ON DELETE SET NULL,
    CONSTRAINT fk_organization_assignments_updated_by FOREIGN KEY (updated_by_user_id) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
