<?php

return [
    'ai/view' => [
        'file' => 'modules/ai/pages/view.php',
        'layout' => true,
        'permission' => 'ai.view',
        'auth' => true,
        'method' => 'GET',
    ],
    'ai/audit' => [
        'file' => 'modules/ai/pages/audit.php',
        'layout' => true,
        'permission' => 'ai.audit.view',
        'auth' => true,
        'method' => 'GET',
    ],
    'ai/schema' => [
        'file' => 'modules/ai/pages/schema.php',
        'layout' => true,
        'permission' => 'ai.view',
        'auth' => true,
        'method' => 'GET',
    ],
    'ai/planner' => [
        'file' => 'modules/ai/pages/planner.php',
        'layout' => true,
        'permission' => 'ai.view',
        'auth' => true,
        'method' => 'GET',
    ],
    'ai/query-flow' => [
        'file' => 'modules/ai/pages/query_flow.php',
        'layout' => true,
        'permission' => 'ai.schema.manage',
        'auth' => true,
        'method' => 'GET',
    ],
    'ai/sql-guard' => [
        'file' => 'modules/ai/pages/sql_guard.php',
        'layout' => true,
        'permission' => 'ai.schema.manage',
        'auth' => true,
        'method' => 'GET',
    ],
    'ai/sql-preview' => [
        'file' => 'modules/ai/pages/sql_preview.php',
        'layout' => true,
        'permission' => 'ai.schema.manage',
        'auth' => true,
        'method' => 'GET',
    ],
    'ai/sql-candidate' => [
        'file' => 'modules/ai/pages/sql_candidate.php',
        'layout' => true,
        'permission' => 'ai.schema.manage',
        'auth' => true,
        'method' => 'GET',
    ],
    'ai/quality' => [
        'file' => 'modules/ai/pages/quality.php',
        'layout' => true,
        'permission' => 'ai.schema.manage',
        'auth' => true,
        'method' => 'GET',
    ],
    'ai/providers' => [
        'file' => 'modules/ai/pages/providers.php',
        'layout' => true,
        'permission' => 'ai.adapters.manage',
        'auth' => true,
        'method' => 'GET',
    ],
    'ai/actions/sync-schema' => [
        'file' => 'modules/ai/actions/sync_schema.php',
        'layout' => false,
        'permission' => 'ai.schema.manage',
        'auth' => true,
        'method' => 'POST',
    ],
    'ai/actions/export-schema' => [
        'file' => 'modules/ai/actions/export_schema.php',
        'layout' => false,
        'permission' => 'ai.view',
        'auth' => true,
        'method' => 'GET',
    ],
    'ai/actions/export-quality' => [
        'file' => 'modules/ai/actions/export_quality.php',
        'layout' => false,
        'permission' => 'ai.schema.manage',
        'auth' => true,
        'method' => 'GET',
    ],
    'ai/actions/provider-update' => [
        'file' => 'modules/ai/actions/provider_update.php',
        'layout' => false,
        'permission' => 'ai.adapters.manage',
        'auth' => true,
        'method' => 'POST',
    ],
    'ai/actions/provider-test' => [
        'file' => 'modules/ai/actions/provider_test.php',
        'layout' => false,
        'permission' => 'ai.adapters.manage',
        'auth' => true,
        'method' => 'POST',
    ],
];
