<?php

return [
    'api/metrics' => [
        'file' => 'modules/api/pages/metrics.php',
        'layout' => true,
        'permission' => 'health.view',
        'auth' => true,
        'method' => 'GET',
    ],
    'api/actions/metrics-export' => [
        'file' => 'modules/api/actions/metrics_export.php',
        'layout' => false,
        'permission' => 'health.view',
        'auth' => true,
        'method' => 'GET',
    ],
    'api/v1' => [
        'file' => 'modules/api/v1/index.php',
        'layout' => false,
        'permission' => null,
        'auth' => false,
        'method' => 'GET',
    ],
    'api/v1/auth/token' => [
        'file' => 'modules/api/v1/auth/token.php',
        'layout' => false,
        'permission' => null,
        'auth' => false,
        'method' => 'POST',
    ],
    'api/v1/me' => [
        'file' => 'modules/api/v1/me.php',
        'layout' => false,
        'permission' => null,
        'auth' => false,
        'method' => 'GET',
    ],
    'api/v1/ai/schema' => [
        'file' => 'modules/api/v1/ai/schema.php',
        'layout' => false,
        'permission' => null,
        'auth' => false,
        'method' => 'GET',
    ],
    'api/v1/ai/schema/search' => [
        'file' => 'modules/api/v1/ai/schema_search.php',
        'layout' => false,
        'permission' => null,
        'auth' => false,
        'method' => 'GET',
    ],
    'api/v1/users' => [
        'file' => 'modules/api/v1/users/index.php',
        'layout' => false,
        'permission' => null,
        'auth' => false,
        'method' => 'ANY',
    ],
    'api/v1/users/{id}' => [
        'file' => 'modules/api/v1/users/update.php',
        'layout' => false,
        'permission' => null,
        'auth' => false,
        'method' => 'PATCH',
    ],
    'api/v1/users/{id}/status' => [
        'file' => 'modules/api/v1/users/status.php',
        'layout' => false,
        'permission' => null,
        'auth' => false,
        'method' => 'POST',
    ],
    'api/v1/postman-collection' => [
        'file' => 'modules/api/v1/postman_collection.php',
        'layout' => false,
        'permission' => null,
        'auth' => false,
        'method' => 'GET',
    ],
    'api/v1/postman' => [
        'file' => 'modules/api/v1/postman_collection.php',
        'layout' => false,
        'permission' => null,
        'auth' => false,
        'method' => 'GET',
    ],
    'api/v1/postman-collection.json' => [
        'file' => 'modules/api/v1/postman_collection.php',
        'layout' => false,
        'permission' => null,
        'auth' => false,
        'method' => 'GET',
    ],
];
